name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select an environment to deploy'
        required: true
        default: 'prd'
        type: choice
        options:
          - prd
          - dev
          - tst

env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.repository }}
  REPO_LINK: https://github.com/${{ github.repository }}
  BRANCH_NAME: ${{ github.ref_name }}
  SELECTED_ENV: ${{ github.event.inputs.environment }}

jobs:
  build_and_push:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set docker image tag name based on branch name
      id: set_env_vars
      run: |
        chmod +x ./.github/scripts/set-env-vars.sh
        ./.github/scripts/set-env-vars.sh
        source ./.github/scripts/set-env-vars.sh
        echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV
        echo "PORTAINER_ENV_VARS=$PORTAINER_ENV_VARS" >> $GITHUB_OUTPUT
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: images/Dockerfile
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.REPO_NAME }}.${{ env.SELECTED_ENV }}:latest
          ${{ env.REGISTRY }}/${{ env.REPO_NAME }}.${{ env.SELECTED_ENV }}:${{ env.BUILD_NUMBER }}
        build-args: |
          BASE_IMAGE=ghcr.io/datntdev0/frappe-base.${{ env.SELECTED_ENV }}
          ERPNEXT_REPO=${{ env.REPO_LINK }}
          ERPNEXT_BRANCH=${{ env.BRANCH_NAME }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    outputs:
      PORTAINER_ENV_VARS: ${{ steps.set_env_vars.outputs.PORTAINER_ENV_VARS }}

  deploy_to_portainer:
    needs: [ build_and_push ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Deploy to Portainer
      uses: datntdev0/action-deploy-to-portainer@v0.1.1
      with:
        portainerHost: ${{ secrets.PORTAINER_HOST }}
        portainerApiKey: ${{ secrets.PORTAINER_API_KEY }}
        portainerEnvId: ${{ secrets.PORTAINER_ENV_ID }}
        portainerStackName: erpnext-${{ env.SELECTED_ENV }}
        portainerFilePath: './images/docker-compose.yml'
        portainerEnvVars: ${{ needs.build_and_push.outputs.PORTAINER_ENV_VARS }}